export const $ = (id) => document.getElementById(id);

export const els = {
  views: document.querySelectorAll(".view"),
  nav: document.querySelectorAll("[data-view]"),
  mainNav: $("mainNav"), menuToggle: $("menuToggle"),
  guideGrid: $("guideGrid"),
  profileSetup: $("profileSetup"), profileForm: $("profileForm"), profileNameInput: $("profileNameInput"), profileWeaponInput: $("profileWeaponInput"), profileExperienceInput: $("profileExperienceInput"), profileYearsInput: $("profileYearsInput"), profileGoalInput: $("profileGoalInput"), profileStyleInput: $("profileStyleInput"),
  levelToast: $("levelToast"), levelToastText: $("levelToastText"), unlockToastText: $("unlockToastText"),
  welcomeLabel: $("welcomeLabel"), hubAvatar: $("hubAvatar"), hubProfileName: $("hubProfileName"), hubProfileStyle: $("hubProfileStyle"), hubLevel: $("hubLevel"), hubXp: $("hubXp"), hubXpFill: $("hubXpFill"), hubMatches: $("hubMatches"), hubAccuracy: $("hubAccuracy"), hubMastered: $("hubMastered"),
  profileAvatar: $("profileAvatar"), profileName: $("profileName"), profileSummary: $("profileSummary"), profileWeapon: $("profileWeapon"), profileExperience: $("profileExperience"), profileStyle: $("profileStyle"), profileYears: $("profileYears"), profileLevel: $("profileLevel"), profileXp: $("profileXp"), profileXpFill: $("profileXpFill"), avatarSelect: $("avatarSelect"),
  statMatches: $("statMatches"), statWins: $("statWins"), statLosses: $("statLosses"), statWinRate: $("statWinRate"), statTouchesScored: $("statTouchesScored"), statTouchesReceived: $("statTouchesReceived"), statAvgRating: $("statAvgRating"), profileSkills: $("profileSkills"),
  strengthList: $("strengthList"), improveList: $("improveList"), skillTree: $("skillTree"),
  progressLevel: $("progressLevel"), progressXp: $("progressXp"), progressMatches: $("progressMatches"), progressAccuracy: $("progressAccuracy"), progressRating: $("progressRating"), progressMastered: $("progressMastered"),
  flashCard: $("flashCard"), flashSide: $("flashSide"), flashText: $("flashText"), flashHint: $("flashHint"),
  quizDifficulty: $("quizDifficulty"), quizMeta: $("quizMeta"), quizScore: $("quizScore"), quizQuestion: $("quizQuestion"), quizOptions: $("quizOptions"), quizFeedback: $("quizFeedback"), nextQuestion: $("nextQuestion"),
  scenarioDifficulty: $("scenarioDifficulty"), scenarioCount: $("scenarioCount"), scenarioDistance: $("scenarioDistance"), scenarioStyle: $("scenarioStyle"), scenarioSituation: $("scenarioSituation"), scenarioOptions: $("scenarioOptions"), scenarioFeedback: $("scenarioFeedback"), nextScenario: $("nextScenario"),
  matchSetup: $("matchSetup"), matchGame: $("matchGame"), duelGame: $("duelGame"), matchAnalysis: $("matchAnalysis"), startMatch: $("startMatch"), simulatorMode: $("simulatorMode"), duelTimerMode: $("duelTimerMode"),
  playerScore: $("playerScore"), opponentScore: $("opponentScore"), matchRatingDisplay: $("matchRatingDisplay"), tacticalScore: $("tacticalScore"), distanceScore: $("distanceScore"), timingScore: $("timingScore"), roundNumber: $("roundNumber"), matchDistance: $("matchDistance"), matchDistanceName: $("matchDistanceName"), youFencer: $("youFencer"), themFencer: $("themFencer"), touchFlash: $("touchFlash"), matchActions: $("matchActions"), sequenceList: $("sequenceList"), sequenceCount: $("sequenceCount"), commitmentText: $("commitmentText"), commitmentFill: $("commitmentFill"), suggestedSequence: $("suggestedSequence"), trySuggestion: $("trySuggestion"), simpleControls: $("simpleControls"), advancedControls: $("advancedControls"), undoSequence: $("undoSequence"), clearSequence: $("clearSequence"), keyboardHint: $("keyboardHint"), matchMode: $("matchMode"), aiDifficulty: $("aiDifficulty"), learningMode: $("learningMode"), opponentType: $("opponentType"), opponentTitle: $("opponentTitle"), aiBehaviour: $("aiBehaviour"), aiPattern: $("aiPattern"), opponentAnalysis: $("opponentAnalysis"), analysisConfidence: $("analysisConfidence"), memoryPanel: $("memoryPanel"), memoryList: $("memoryList"), aiAdjustment: $("aiAdjustment"), observationPanel: $("observationPanel"), observationList: $("observationList"), historyPanel: $("historyPanel"), exchangeHistory: $("exchangeHistory"), patternPanel: $("patternPanel"), detectedPattern: $("detectedPattern"), matchSituation: $("matchSituation"), matchFeedback: $("matchFeedback"), analysisOutcome: $("analysisOutcome"), analysisPlayerAction: $("analysisPlayerAction"), analysisOpponentAction: $("analysisOpponentAction"), analysisResult: $("analysisResult"), analysisTacticalPoints: $("analysisTacticalPoints"), analysisSkillXp: $("analysisSkillXp"), nextExchange: $("nextExchange"), replayExchange: $("replayExchange"), analysisResetMatch: $("analysisResetMatch"),
  duelP1Score: $("duelP1Score"), duelP2Score: $("duelP2Score"), duelExchange: $("duelExchange"), duelTempo: $("duelTempo"), duelP1Fencer: $("duelP1Fencer"), duelP2Fencer: $("duelP2Fencer"), duelTouchFlash: $("duelTouchFlash"), duelDistance: $("duelDistance"), duelDistanceName: $("duelDistanceName"), duelPhaseLabel: $("duelPhaseLabel"), duelStatus: $("duelStatus"), duelP1Action: $("duelP1Action"), duelP2Action: $("duelP2Action"), duelP1Plan: $("duelP1Plan"), duelP2Plan: $("duelP2Plan"), duelEventLog: $("duelEventLog"), resetDuel: $("resetDuel"), lockDuelPlan: $("lockDuelPlan"), duelPlayerReady: $("duelPlayerReady"), clearDuelPlan: $("clearDuelPlan")
};
